name: blank
options:
  bundleIdPrefix: com.blank 
targets:
  blank:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources: [Sources]
    info:
      path: Info.plist
      properties:
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.blank 
        SWIFT_VERSION: "5.0"
        PRODUCT_NAME: blank
